version: "3.8"

services:
  db: # name of the service (Docker DNS will use it into Docker internal network)
    build: 
      context: ./database #folder with the dockerfile for this service
    ports: 
      - 5432:5432 
    environment:
      POSTGRES_PASSWORD: test123
      POSTGRES_USER: myuser
      POSTGRES_DB: webapp_db
    volumes: 
      - webapp:/var/lib/postgresql/data
    networks:
      - internalnet

  api: # name of the fastapi service
    build: ./backend #folder with the dockerfile for the fastapi server
    ports: 
      - 8000:8000 
    environment:
      DATABASE_URL: "postgresql://myuser:test123@db:5432/webapp_db"
    networks:
      - internalnet
    
    depends_on: 
      - db

volumes:
  webapp:

networks:
  internalnet:
    driver: bridge